### ISSUE TITLE
WHMCS License being required for reissue most builds

### ISSUE THREAD

**Issue by Edbtvplays** [EdyTheCow/docker-whmcs#1]
About 1 in every 2-3 times i restart the docker-compose file for WHMCS, it requires me to reissue the WHMCS License on whmcs.com, i believe this to be because WHMCS is seeing the docker IP Address as its main and it is changing when i restart the docker-compose file. Is there any way around this?

**Comment by EdyTheCow** [comment]
Is your WHMCS container running under Traefik or something else?

**Comment by Edbtvplays** [comment]
We are indeed running it under traefik.
