### ISSUE TITLE
network global declared as external, but could not be found

### ISSUE THREAD

**Issue by taraszka** [EdyTheCow/docker-whmcs#11]
```
# docker compose up -d
network global declared as external, but could not be found
```

is seems `docker-whmcs` expects that the network exists. Is it worth mentioning this in the README?

**Comment by EdyTheCow** [comment]
Thank you for pointing it out, will add it to readme. It's probably also good idea to be more specific with it like `docker-whmcs-network` just to avoid possible conflicts.

To create external network is as simple as: `docker network create global`
