### ISSUE TITLE
Can't access domain.com/install

### ISSUE THREAD

**Issue by morganzero** [EdyTheCow/docker-whmcs#3]
Hi,

And firstly, thank you for making it possible to run WHMCS through docker I've been waiting for this solution for a long time, so great work!

However, I'm experiencing an issue where I'm not able to access mydomain.com/install. All I get is a "404 page not found" when I visit it. I've read through the README page about a hundred times and can't wrap my head around this issue.

Any ideas that could lead me to an avenue to correct this?

Thanks!

**Comment by EdyTheCow** [comment]
Apologies for late respond, does domain.com give you 404 error also? Maybe you've uploaded the WHMCS files to a wrong directory?
