### ISSUE TITLE
Invalid License

### ISSUE THREAD

**Issue by dkraklan** [EdyTheCow/docker-whmcs#6]
After running through the install I'm getting an invalid license and WHMCS refuses to license, 8.6.1. I've tested with the /admin/login.php?conntest=1 and both tests succeed, I can see the request leaving the php-fpm container and getting a response. It can resolve them from the CLI. 

Testing Connection to 'https://a.licensing.whmcs.com/1.0/test'...
URL resolves to 208.74.120.154 ...
Response Code: 200
Connection Successful!

Testing Connection to 'https://b.licensing.whmcs.com/1.0/test'...
URL resolves to 184.94.192.12 ...
Response Code: 200
Connection Successful!

**Comment by EdyTheCow** [comment]
The issue #2 might have a solution which I haven't gotten around of testing. I'll try to dedicate some time this week to look into this. My own installation does validate the license but the IP shown on WHMCS license page is 127.0.0.1, which makes me wonder how that even works haha
